import Link from 'next/link';
import { PlusCircle } from 'lucide-react';
import { getSupabaseServerClient } from '@/lib/supabase/server';
import { isConfigured, formatDate, formatDateTime, formatMoney, formatNumber } from '@/lib/utils';
import { Card } from '@/components/card';
import type { PaymentRun } from '@/lib/types';

export const dynamic = 'force-dynamic';

export default async function DashboardPage() {
  if (!isConfigured()) {
    return <NotConfigured />;
  }

  const supabase = await getSupabaseServerClient();
  const { data: runs, error } = await supabase
    .from('payment_runs')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(100);

  const paymentRuns = (runs ?? []) as unknown as PaymentRun[];

  return (
    <div className="space-y-6">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Payment runs</h1>
          <p className="text-sm text-muted-foreground">
            History of rider payment workbooks generated by the team.
          </p>
        </div>
        <Link
          href="/new"
          className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground text-sm font-medium px-4 py-2 hover:opacity-90"
        >
          <PlusCircle className="w-4 h-4" />
          New payment run
        </Link>
      </header>

      {error ? (
        <Card>
          <div className="text-sm text-danger">Failed to load payment runs: {error.message}</div>
        </Card>
      ) : paymentRuns.length === 0 ? (
        <EmptyState />
      ) : (
        <Card>
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs uppercase tracking-wider text-muted-foreground border-b border-border">
                <th className="py-2 pr-4">Period</th>
                <th className="py-2 pr-4">Created</th>
                <th className="py-2 pr-4">By</th>
                <th className="py-2 pr-4">Status</th>
                <th className="py-2 pr-4 text-right">Riders</th>
                <th className="py-2 pr-4 text-right">Orders</th>
                <th className="py-2 pr-4 text-right">Total</th>
                <th className="py-2 pr-4"></th>
              </tr>
            </thead>
            <tbody>
              {paymentRuns.map((run) => (
                <tr key={run.id} className="border-b border-border last:border-0">
                  <td className="py-3 pr-4">
                    <Link href={`/runs/${run.id}`} className="font-medium hover:underline">
                      {run.period_label}
                    </Link>
                    <div className="text-xs text-muted-foreground">
                      {formatDate(run.period_start)} – {formatDate(run.period_end)}
                    </div>
                  </td>
                  <td className="py-3 pr-4 text-muted-foreground text-xs">
                    {formatDateTime(run.created_at)}
                  </td>
                  <td className="py-3 pr-4 text-muted-foreground text-xs truncate max-w-[180px]">
                    {run.created_by_email}
                  </td>
                  <td className="py-3 pr-4">
                    <StatusBadge status={run.status} />
                  </td>
                  <td className="py-3 pr-4 text-right tabular-nums">
                    {formatNumber(run.rider_count)}
                  </td>
                  <td className="py-3 pr-4 text-right tabular-nums">
                    {formatNumber(run.order_count)}
                  </td>
                  <td className="py-3 pr-4 text-right tabular-nums">
                    {formatMoney(run.total_amount)}
                  </td>
                  <td className="py-3 pr-4 text-right">
                    {run.status === 'complete' ? (
                      <a
                        href={`/api/payment-runs/${run.id}/download`}
                        className="text-xs text-accent hover:underline"
                      >
                        Download
                      </a>
                    ) : null}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    processing: 'bg-warning/10 text-warning border-warning/30',
    complete: 'bg-success/10 text-success border-success/30',
    error: 'bg-danger/10 text-danger border-danger/30',
  };
  return (
    <span
      className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${styles[status] ?? ''}`}
    >
      {status}
    </span>
  );
}

function EmptyState() {
  return (
    <Card>
      <div className="py-12 text-center">
        <h2 className="text-lg font-medium">No payment runs yet</h2>
        <p className="text-sm text-muted-foreground mt-1 mb-4">
          Create your first payment run to generate a rider payment workbook.
        </p>
        <Link
          href="/new"
          className="inline-flex items-center gap-2 rounded-md bg-primary text-primary-foreground text-sm font-medium px-4 py-2 hover:opacity-90"
        >
          <PlusCircle className="w-4 h-4" />
          New payment run
        </Link>
      </div>
    </Card>
  );
}

function NotConfigured() {
  return (
    <div className="rounded-md border border-warning/30 bg-warning/10 p-4 text-sm">
      Supabase env vars not set. See <code>.env.example</code>.
    </div>
  );
}
